AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: | 
  This stack creates the S3 bucket a web application

Parameters:
  AppNameParameter:
    Description: "App Name"
    Type: String
  GuidParameter:
    Description: "Guid"
    Type: String
  OriginAccessIdentityParameter:
    Description: "Origin Access Identity"
    Type: String
  OriginAccessControlParameter:
    Description: "Origin Access Control"
    Type: String

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'app-${AppNameParameter}-${GuidParameter}'

  StoreAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentityParameter}'
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AppBucket}/*'

Outputs:
  AppBucket:
    Description: The Store App Bucket
    Value: !Ref AppBucket
