AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: | 
  This stack creates the persistent resources for the web applications 
  in our system.

Parameters:
  GuidParameter:
    Description: "Guid"
    Type: String

Resources:
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for accessing S3 bucket"

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: Lzm-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  AppAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'app-assets-${GuidParameter}'

  AppAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppAssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}'
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AppAssetsBucket}/*'


  StoreAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'app-store-${GuidParameter}'

  StoreAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StoreAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}'
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${StoreAppBucket}/*'

  ConsumerAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'app-consumer-${GuidParameter}'

  ConsumerAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConsumerAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}'
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${ConsumerAppBucket}/*'

Outputs:
  OriginAccessIdentity:
    Description: The Origin Access Identity
    Value:
      Ref: OriginAccessIdentity
  OriginAccessControl:
    Description: The Origin Access Control
    Value: !GetAtt 'OriginAccessControl.Id'
  AppAssetsBucket:
    Description: The App Assets Bucket
    Value: !Ref AppAssetsBucket
  StoreAppBucket:
    Description: The Store App Bucket
    Value: !Ref StoreAppBucket
  ConsumerAppBucket:
    Description: The Consumer App Bucket
    Value: !Ref ConsumerAppBucket