  __LambdaName__:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: ../../__OutputDir__/__LambdaName__/bin/Release/net8.0
      Handler: __LambdaName__::LambdaFunc.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnet8
      Description: LazyMagic Generated WebSocket Function
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName: '*'
      - Statement:
        - Effect: Allow
          Action:
          - execute-api:ManageConnections
          Resource:
            Fn::Sub: arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${__Resource1__}/*/*
      Environment:
        Variables:
          COGNITO_REGION:
            Ref: AWS::Region
