
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${SubDomainParameter}.${RootDomainParameter}'
        Comment: !Sub '${AWS::StackName}-${TenantKeyParameter}'
        Logging:
          Bucket: !Sub 'cdnlogs-${TenantKeyParameter}-${GuidParameter}.s3.amazonaws.com'
          IncludeCookies: false 
          Prefix: !Sub '${TenantKeyParameter}/'

        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: true
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArnParameter
          MinimumProtocolVersion: 'TLSv1.1_2016'
          SslSupportMethod: 'sni-only'

        DefaultCacheBehavior: 
          TargetOriginId: TenancyConfigOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
          CachePolicyId: !Ref CachePolicyIdParameter
          OriginRequestPolicyId: !Ref OriginRequestPolicyIdParameter
          ResponseHeadersPolicyId: !GetAtt ResponseHeadersPolicy.Id
          FunctionAssociations:
            - EventType: 'viewer-request'
              FunctionARN: !GetAtt LandingPageFunction.FunctionARN
            # - EventType: 'viewer-response'
            #   FunctionARN: !Ref ResponseFunctionArnParameter

        #Logging:
        #  Bucket: !Sub '${CDNLogsBucketParameter}.s3.amazonaws.com'
        #  IncludeCookies: false 
        #  Prefix: !Sub '${AWS::StackName}/'

        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/404.html'
          - ErrorCachingMinTTL: 60
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: '/index.html'

        CacheBehaviors:

          - PathPattern: '/Tenancy/*'
            TargetOriginId: TenancyConfigOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            ResponseHeadersPolicyId: !GetAtt ResponseHeadersPolicy.Id
            CachePolicyId: !Ref CachePolicyIdParameter
            FunctionAssociations:
              - EventType: 'viewer-request'
                FunctionARN: !Ref RequestFunctionArnParameter
              # - EventType: 'viewer-response'
              #   FunctionARN: !Ref ResponseFunctionArnParameter

          - PathPattern: '/Assets/*'
            TargetOriginId: AssetsConfigOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            ResponseHeadersPolicyId: !GetAtt ResponseHeadersPolicy.Id
            CachePolicyId: !Ref CachePolicyIdParameter
            FunctionAssociations:
              - EventType: 'viewer-request'
                FunctionARN: !Ref RequestFunctionArnParameter
              # - EventType: 'viewer-response'
              #   FunctionARN: !Ref ResponseFunctionArnParameter

          - PathPattern: '/config'
            TargetOriginId: TenancyConfigOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            CachePolicyId: !Ref CachePolicyIdParameter
            OriginRequestPolicyId: !Ref OriginRequestPolicyIdParameter
            ResponseHeadersPolicyId: !GetAtt ResponseHeadersPolicy.Id
            FunctionAssociations:
              - EventType: 'viewer-request'
                FunctionARN: !GetAtt ConfigFunction.FunctionARN
              # - EventType: 'viewer-response'
              #   FunctionARN: !Ref ResponseFunctionArnParameter

          # Generated webapp cache behaviors
#LzCacheBehaviors#         

        Origins:
          # Origin serving tenancy config
          - Id: TenancyConfigOrigin
            DomainName: !Sub 'config-${TenantKeyParameter}-${GuidParameter}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentityParameter}'

          - Id: AssetsConfigOrigin
            DomainName: !Sub '${AppAssetsBucketNameParameter}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentityParameter}'


           # LazyMagic generated webapp origins
#LzWebAppOrigins#

           # LazyMagic generated api origins
#LzApiOrigins#

           # LazyMagic generated websocket origins  
#LzWsOrigins#

  # LazyMagic generated config function
#LzConfigFunction#

  # LazyMagic generated landing page function
#LzLandingPageFunction#


  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Condition: HasSubDomain 
    Properties:
      HostedZoneId: !Ref HostedZoneIdParameter
      RecordSets:
      - Name: !Sub '${SubDomainParameter}.${RootDomainParameter}'
        Type: 'A'
        AliasTarget:
          DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
          EvaluateTargetHealth: false
          # The  following HostedZoneIdParameter is always used for alias records pointing to CF.
          HostedZoneId: 'Z2FDTNDATAQYW2' 
